name: Run All scripts

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for trigger'
        required: false

permissions:
  contents: read     # Standard read permission is usually enough here
  actions: write     # Needed if you manage B's own workflows, but not strictly needed to trigger A's
  statuses: write

jobs:
  python-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trigger Remote Workflow with gh
        env:
          # The GH CLI automatically looks for GH_TOKEN or GITHUB_TOKEN
          GH_TOKEN: ${{ secrets.TRIGGER_PAT_AQWERTYUIOP48 }}
        run: |
          gh workflow run trigger-branches.yml --repo aqwertyuiop48/vercel_docker_programming --ref main

          gh workflow run bitbucket_sreebitbucket19.yml --repo aqwertyuiop48/leetcode_programming --ref main
          gh workflow run gitlab_sreegithub19.yml --repo aqwertyuiop48/leetcode_programming --ref main
          gh workflow run trigger_gitforcode_debug.yml --repo aqwertyuiop48/leetcode_programming --ref main
          gh workflow run vercel_repos.yml --repo aqwertyuiop48/leetcode_programming --ref main
          gh workflow run vercel_repos_1.yml --repo aqwertyuiop48/leetcode_programming --ref main
          gh workflow run vercel_repos_2.yml --repo aqwertyuiop48/leetcode_programming --ref main
          gh workflow run trigger_repos.yml --repo aqwertyuiop48/leetcode_programming --ref main
          gh workflow run trigger_repos1.yml --repo aqwertyuiop48/leetcode_programming --ref main
          gh workflow run render_.yml --repo aqwertyuiop48/leetcode_programming --ref main
          gh workflow run render_1.yml --repo aqwertyuiop48/leetcode_programming --ref main

          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "main.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "trigger-all.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab-cnn-chunks-9-10.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab-cnn-chunks-9-10_1.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab-cnn-chunks-9-10_2.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab-cnn-chunks-9-10_3.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab-cnn-chunks-9-10_4.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab-cnn-chunks-9-10_5.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab-cnn-chunks-9-10_6.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab-cnn-chunks-9-10_7.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab_Lead_Scoring_ALL_IN_ONE_COLAB.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab_gesture_recognition_1_2_3.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab_gesture_recognition_4_5.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab_gesture_recognition_6_7_8.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab_gesture_recognition_9_10.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab_skin_cancer_detection_melanoma.yml"
          gh workflow run --repo aqwertyuiop48/upgrad_programming_1 --ref main1 "gcolab_working-with-chest-xray-images.yml"
